DROP TABLE IF EXISTS ArchiveEntry;
DROP TABLE IF EXISTS post;

CREATE TABLE archive_entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  archive_type TEXT UNIQUE NOT NULL,
  archive_source TEXT NOT NULL
);

CREATE TABLE URI_R (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (archive_entry_id) REFERENCES archive_entry (id)
);